export const SET_PROFILE = 'SET_PROFILE';
export const SET_STATUS = 'SET_STATUS';
export const ON_ISFETCHING = 'ON_ISFETCHING';
export const OFF_ISFETCHING = 'OFF_ISFETCHING';
export const SET_USE_PHOTO = 'SET_USE_PHOTO';
export const ON_PHOTO_LOADER = 'ON_PHOTO_LOADER';
export const OFF_PHOTO_LOADER = 'OFF_PHOTO_LOADE';
export const UDPATE_PROFILE = 'UDPATE_PROFILE';